-- --TODO: find where NotoDB is
-- function find_dbmark_location()
-- 	--
-- end
--
-- --
--
-- -- SHOWING
-- -- TODO fh: Find DB mark is
--
-- -- TODO: Expand mark to DB viewpot size
-- function expand_dbmak_to_viewport_size()
-- 	--
-- end
--
-- -- TODO: Open Viewport window for each db
-- function create_viewport(location, size)
-- 	--
-- end
--
-- --
